name: Build and Push Images

on:
  push:
    branches:
      - main
    paths:
      - 'base/**'
      - 'datasci/**'
      - 'dev/**'
      - 'infra/**'
      - '.github/workflows/build-images.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_REPO: coder-images

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ubuntu, ubi9]
        include:
          - variant: ubuntu
            version: "24.04"
          - variant: ubi9
            version: "9.6"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base-${{ matrix.variant }} image
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./base/${{ matrix.variant }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-base-${{ matrix.variant }}:${{ matrix.version }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-base-${{ matrix.variant }}:latest
          cache-from: type=gha,scope=base-${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=base-${{ matrix.variant }}
          platforms: linux/amd64

  # Build datasci-python (depends on respective base images)
  build-datasci-python:
    needs: build-base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ubuntu, ubi9]
        include:
          - variant: ubuntu
            version: "24.04"
          - variant: ubi9
            version: "9.6"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push datasci-python-${{ matrix.variant }} image
        uses: docker/build-push-action@v5
        with:
          context: ./datasci/python
          file: ./datasci/python/${{ matrix.variant }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-datasci-python-${{ matrix.variant }}:${{ matrix.version }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-datasci-python-${{ matrix.variant }}:latest
          cache-from: type=gha,scope=datasci-python-${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=datasci-python-${{ matrix.variant }}
          platforms: linux/amd64

  # Build other datasci images per variant (depend on datasci-python)
  build-datasci-variants:
    needs: build-datasci-python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ubuntu, ubi9]
        type: [pytorch, tensorflow, ml]
        include:
          - variant: ubuntu
            version: "24.04"
          - variant: ubi9
            version: "9.6"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push datasci-${{ matrix.type }}-${{ matrix.variant }} image
        uses: docker/build-push-action@v5
        with:
          context: ./datasci/${{ matrix.type }}
          file: ./datasci/${{ matrix.type }}/${{ matrix.variant }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-datasci-${{ matrix.type }}-${{ matrix.variant }}:${{ matrix.version }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-datasci-${{ matrix.type }}-${{ matrix.variant }}:latest
          cache-from: type=gha,scope=datasci-${{ matrix.type }}-${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=datasci-${{ matrix.type }}-${{ matrix.variant }}
          platforms: linux/amd64

  # Build dev images per variant (depend on base)
  build-dev-variants:
    needs: build-base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ubuntu, ubi9]
        type: [go, rust, java]
        include:
          - variant: ubuntu
            version: "24.04"
          - variant: ubi9
            version: "9.6"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev-${{ matrix.type }}-${{ matrix.variant }} image
        uses: docker/build-push-action@v5
        with:
          context: ./dev/${{ matrix.type }}
          file: ./dev/${{ matrix.type }}/${{ matrix.variant }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-dev-${{ matrix.type }}-${{ matrix.variant }}:${{ matrix.version }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-dev-${{ matrix.type }}-${{ matrix.variant }}:latest
          cache-from: type=gha,scope=dev-${{ matrix.type }}-${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=dev-${{ matrix.type }}-${{ matrix.variant }}
          platforms: linux/amd64

  # Build infra images per variant (depend on base)
  build-infra-variants:
    needs: build-base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ubuntu, ubi9]
        type: [k8s, terraform, ansible, cloud]
        include:
          - variant: ubuntu
            version: "24.04"
          - variant: ubi9
            version: "9.6"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push infra-${{ matrix.type }}-${{ matrix.variant }} image
        uses: docker/build-push-action@v5
        with:
          context: ./infra/${{ matrix.type }}
          file: ./infra/${{ matrix.type }}/${{ matrix.variant }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-infra-${{ matrix.type }}-${{ matrix.variant }}:${{ matrix.version }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/coder-infra-${{ matrix.type }}-${{ matrix.variant }}:latest
          cache-from: type=gha,scope=infra-${{ matrix.type }}-${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=infra-${{ matrix.type }}-${{ matrix.variant }}
          platforms: linux/amd64
